# Generated by Django 5.1.4 on 2024-12-07 14:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinf',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
